---
- name: Task 2 - Firewalls
  hosts: mysql.local
  become: true
  gather_facts: false

  tasks:
    - name: Open firewall for port 3306 on all group web members
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ item }}" #from inventory as variable
        jump: ACCEPT
        protocol: tcp
        destination_port: 3306
        comment: "Basic version"
      loop:
       - 192.168.1.101/32
       - 192.168.1.102/32
       - 192.168.1.103/32